const FREE_MEALS_URL = process.env.FREE_MEALS_URL;
const INVOLVEMENT_URL = process.env.INVOLVEMENT_URL;
const FREE_MEALS_API_KEY = process.env.FREE_MEALS_API_KEY;
const INVOLVEMENT_API_KEY = process.env.INVOLVEMENT_API_KEY;

export {
  FREE_MEALS_URL,
  INVOLVEMENT_URL,
  FREE_MEALS_API_KEY,
  INVOLVEMENT_API_KEY
};

