const {
  FREE_MEALS_URL,
  INVOLVEMENT_URL,
  FREE_MEALS_API_KEY,
  INVOLVEMENT_API_KEY
} = process.env;

export {
  FREE_MEALS_URL,
  INVOLVEMENT_URL,
  FREE_MEALS_API_KEY,
  INVOLVEMENT_API_KEY,
};